services:
  # web:
  #   build: .
  #   ports:
  #     - "80:8000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   command: ["python", "main.py"]
 
  db:
    container_name: simple_psql
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: simpledb
      POSTGRES_USER: simpleuser
      POSTGRES_PASSWORD: complexpassword
    # volumes: # persist data
    #    - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # healthcheck:
    #   test: [“CMD-SHELL”, “pg_isready”]
    #   interval: 1s
    #   timeout: 5s
    #   retries: 10d
 
  pgadmin:
    container_name: simple_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com # TODO: Try changing this
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"